### ISSUE TITLE
https://github-contributions-api.now.sh/ seems to be down

### ISSUE THREAD

**Issue by jonico** [GMartigny/gh.midi#2]
👋  @GMartigny, I have used your project in the past and wanted to feature it as part of the GitHub DACH Winterfest coming up. When I tested today, I noticed that https://github-contributions-api.now.sh/ seems to be down and hence no midis any more 😢 
I would completely understand if you decided not to keep this service alive, but in case it was just an oversight, please let me know so that I can still feature your project 😊 

:octocat: ❤️

**Comment by GMartigny** [comment]
Hi @jonico,
Thanks for the heads up and glad someone found this stupid project funny 😄.
I just updated the link to the API and gh.midi is back live.
Cheers 😎

**Comment by jonico** [comment]
Thank you so much and will invite you to Winterfest!

**Comment by GMartigny** [comment]
Can't wait 😉

**Comment by jonico** [comment]
[Here](https://resources.github.com/webcasts/GitHub-Winterfest-Dach/?utm_source=github&utm_medium=email&utm_campaign=sales-invite) is your invitation to Winterfest ☃️
